music/history/urls.py
from django.urls import path

from . import views

app_name = 'history'
urlpatterns = [
    # path for artists
    path('', views.index, name='index'),
    # path for artist detail
    path('<int:artist_id>/', views.detail, name='detail'),

    path('songs/add/', views.add_song_form, name='add_song_form'),
    path('songs/post/', views.post_song, name='post_song'),

    path('artists/add', views.add_artist_form, name='add_artist_form'),
    path('artists/post', views.post_artist, name='post_artist'),

    path('songs/<int:song_id>/', views.song_detail, name='song_detail'),
]

music/music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('history/', include('history.urls')),
]

music/history/models.py
from django.db import models

# Create your models here.

class Artist(models.Model):
    artist_name = models.CharField(max_length=50)

    def __str__(self):
      return self.artist_name


class Song(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    song_title = models.CharField(max_length=100)

    def __str__(self):
        return self.song_title

music/history/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .models import Artist
from .models import Song

# Create your views here.
def index(request):
    artist_list = Artist.objects.all()
    context = {'artist_list': artist_list}
    return render(request, 'history/index.html', context)

def detail(request, artist_id):
    artist = get_object_or_404(Artist, pk=artist_id)
    artist_songs = Song.objects.filter(artist_id=artist_id)
    context = {'artist': artist, 'songs': artist_songs}
    print(context)
    return render(request, 'history/detail.html', context)

def song_detail(request, song_id):
    song = get_object_or_404(Song, pk=song_id)
    # in the process of creating a song detail page where the artist is clickable
    # song_artist = Artist.objects.filter(song.artist_id=artist)
    context = {'song': song}
    return render(request, 'history/songs/song_detail.html', context)


def add_song_form(request):
    artist_list = Artist.objects.all()
    context = {'artist_list': artist_list}
    return render(request, 'history/add_song.html', context)


def post_song(request):
    song = request.POST["song_title"]
    artist = request.POST["selected_artist"]
    new_song = Song(song_title=song ,artist_id=artist)
    new_song.save()
    return HttpResponseRedirect(reverse('history:index'))

def add_artist_form(request):
    return render(request, 'history/add_artist.html')

def post_artist(request):
    artist = request.POST["artist_name"]
    new_artist = Artist(artist_name=artist)
    new_artist.save()
    return HttpResponseRedirect(reverse('history:index'))

music/history/templates/history/add_artist.html
<h1>Add New artist</h1>
<form action="{% url 'history:post_artist' %}" method="POST">
  {% csrf_token %}
    <label for="artist_name">Artist Name:</label>
    <input id="artist_name" type="text" name="artist_name">
    <input type="submit" value="OK">
</form>

music/history/templates/history/add_song.html
<h1>Add New Song</h1>
<form action="{% url 'history:post_song' %}" method="POST">
  {% csrf_token %}
    <label for="song_title">Song Title:</label>
    <input id="song_title" type="text" name="song_title">


    <label for="artist">Artist:</label>
    <select name="selected_artist">
      {% for artist in artist_list %}
      <option value="{{artist.id}}" id="{{artist.id}}">{{artist.artist_name}}</option>
      {% endfor %}
    </select>

    <input type="submit" value="OK">
</form>

music/history/templates/history/detail.html
{% if artist %}
    <p>{{ artist.artist_name }}</p>
    <ul>
    {% for song in songs %}
        <li><a href="/history/songs/{{ song.id }}/">{{ song.song_title }}</a></li>
    {% endfor %}
    </ul>

    <p><a href="{% url 'history:add_song_form' %}">add song</a></p>


{% else %}
    <p>No artists in the database.</p>
{% endif %}

music/history/templates/history/index.html
{% if artist_list %}
<p>Bands</p>
    <ul>
    {% for artist in artist_list %}
        <li><a href="/history/{{ artist.id }}/">{{ artist.artist_name }}</a></li>
    {% endfor %}
    </ul>

<p><a href="{% url 'history:add_artist_form' %}">add artist</a></p>
{% else %}
    <p>No artists in the database.</p>
{% endif %}

music/history/templates/history/name.html
<form action="/your-name/" method="post">
  {% csrf_token %}
  {{ form }}
  <input type="submit" value="Submit">
</form>

music/history/templates/history/songs/song_detail.html
{% if song %}
    <ul>
        <li>{{ song.song_title }} by <a href="/history/{{ song.artist_id }}/">{{ song.artist.artist_name }}</a></li>
    </ul>
{% else %}
    <p>No artists in the database.</p>
{% endif %}